version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'bank_core_db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'rAgM@!_2?t(JC$2'
      MYSQL_ROOT_PASSWORD: 'rAgM@!_2?t(JC$2'
    ports:
      - "3307:3306"