version: '3.8'
services:
  app:
    build: .
    ports:
      - "8081:8080"
    depends_on:
      - db
      - rabbitmq
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'bank_core_db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'rAgM@!_2?t(JC2'
      MYSQL_ROOT_PASSWORD: 'rAgM@!_2?t(JC2'
    ports:
      - "3307:3306"
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - "./rabbitmq_data:/var/lib/rabbitmq"
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password