openapi: 3.0.0
info:
  title: Banking API
  version: 1.0.0
paths:
  /client/account/{accountId}:
    get:
      summary: Get account details
      parameters:
        - name: accountId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Account details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
        '400':
          description: Invalid account ID

  /client/userId/by-account/{accountId}:
    get:
      summary: Get user ID by account
      parameters:
        - name: accountId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: User ID
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserInfoDto'
        '400':
          description: Invalid account ID

  /client/openAccount/{userId}:
    post:
      summary: Open a new account
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateAccountDTO'
      responses:
        '201':
          description: Account created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
        '400':
          description: Invalid user ID or request body
  /client/closeAccount/{accountId}:
    post:
      summary: Close an account
      parameters:
        - name: accountId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Account closed successfully
        '400':
          description: Invalid account ID

  /client/deposit:
    post:
      summary: Deposit money into an account
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DepositDTO'
      responses:
        '200':
          description: Deposit successful
        '400':
          description: Invalid request

  /client/withdraw:
    post:
      summary: Withdraw money from an account
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WithdrawDTO'
      responses:
        '200':
          description: Withdrawal successful
        '400':
          description: Invalid request

  /client/transfer:
    post:
      summary: Transfer money between accounts
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransferRequestDTO'
      responses:
        '200':
          description: Transfer successful
        '400':
          description: Invalid request

  /client/transactions/{accountId}:
    get:
      summary: Get transactions for an account
      parameters:
        - name: accountId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: List of transactions
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Transaction'
        '400':
          description: Invalid account ID
  /employee/accounts:
    get:
      summary: Get a list of all accounts
      responses:
        '200':
          description: List of all accounts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Account'

  /employee/users:
    get:
      summary: Get all unique users with an account
      responses:
        '200':
          description: List of all unique users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserInfoDto'

  /employee/account/{accountId}/transactions:
    get:
      summary: Get transactions for a specific account
      parameters:
        - name: accountId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: List of transactions for the account
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Transaction'
        '400':
          description: Invalid account ID
components:
  schemas:
    Account:
      type: object
      properties:
        id:
          type: integer
        balance:
          type: number
        currencyType:
          type: string
        accountType:
          type: string
        interestRate:
          type: number
    UserInfoDto:
      type: object
      properties:
        userId:
          type: string
    CreateAccountDTO:
      type: object
      properties:
        initialDeposit:
          type: number
        currencyType:
          type: string
        accountType:
          type: string
        interestRate:
          type: number
    DepositDTO:
      type: object
      properties:
        accountId:
          type: integer
        amount:
          type: number
        currencyType:
          type: string

    WithdrawDTO:
      type: object
      properties:
        accountId:
          type: integer
        amount:
          type: number
        currencyType:
          type: string

    TransferRequestDTO:
      type: object
      properties:
        fromAccountId:
          type: integer
        toAccountId:
          type: integer
        amount:
          type: number
        currencyType:
          type: string

    Transaction:
      type: object
      properties:
        id:
          type: integer
        amount:
          type: number
        fromAccountId:
          type: integer
        toAccountId:
          type: integer
        transactionType:
          type: string
        currencyType:
          type: string